"""Export documentation to Markdown, HTML, or ZIP."""

from __future__ import annotations

import io
import zipfile


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>{title}</title>
  <style>
    :root {{
      --bg: #0d1117;
      --surface: #161b22;
      --border: #30363d;
      --text: #e6edf3;
      --text-muted: #8b949e;
      --accent: #58a6ff;
      --green: #3fb950;
      --yellow: #d29922;
      --red: #f85149;
      --code-bg: #1f2937;
    }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.7;
      padding: 2rem;
      max-width: 900px;
      margin: 0 auto;
    }}
    h1, h2, h3, h4 {{
      color: var(--text);
      margin: 1.5rem 0 0.5rem;
      font-weight: 600;
    }}
    h1 {{ font-size: 2rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
    h2 {{ font-size: 1.5rem; color: var(--accent); }}
    h3 {{ font-size: 1.2rem; }}
    p {{ margin: 0.75rem 0; color: var(--text-muted); }}
    a {{ color: var(--accent); text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    code {{
      font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace;
      background: var(--code-bg);
      color: #e2e8f0;
      padding: 0.15em 0.4em;
      border-radius: 4px;
      font-size: 0.9em;
    }}
    pre {{
      background: var(--code-bg);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 1.25rem;
      overflow-x: auto;
      margin: 1rem 0;
    }}
    pre code {{ background: none; padding: 0; font-size: 0.875rem; }}
    table {{
      width: 100%;
      border-collapse: collapse;
      margin: 1rem 0;
      font-size: 0.9rem;
    }}
    th {{
      background: var(--surface);
      color: var(--text);
      padding: 0.6rem 1rem;
      text-align: left;
      border: 1px solid var(--border);
    }}
    td {{
      padding: 0.5rem 1rem;
      border: 1px solid var(--border);
      color: var(--text-muted);
    }}
    tr:nth-child(even) td {{ background: var(--surface); }}
    blockquote {{
      border-left: 3px solid var(--accent);
      padding: 0.5rem 1rem;
      margin: 1rem 0;
      background: var(--surface);
      border-radius: 0 6px 6px 0;
      color: var(--text-muted);
    }}
    ul, ol {{ padding-left: 1.5rem; margin: 0.5rem 0; }}
    li {{ margin: 0.3rem 0; color: var(--text-muted); }}
    hr {{ border: none; border-top: 1px solid var(--border); margin: 2rem 0; }}
    .badge {{
      display: inline-block;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 20px;
      padding: 0.2em 0.7em;
      font-size: 0.8em;
      margin-right: 0.3em;
      color: var(--accent);
    }}
    .header {{
      display: flex;
      align-items: center;
      gap: 1rem;
      margin-bottom: 2rem;
      padding-bottom: 1rem;
      border-bottom: 1px solid var(--border);
    }}
    .generated-by {{
      color: var(--text-muted);
      font-size: 0.85rem;
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid var(--border);
      text-align: center;
    }}
  </style>
</head>
<body>
  {body}
  <div class="generated-by">⚡ Generated by <strong>TechDoc AI Agent</strong> · Powered by Claude</div>
</body>
</html>"""


class DocExporter:
    """Exports generated documentation to various formats."""

    def to_markdown(self, content: str, filename: str = "documentation.md") -> bytes:
        """
        Return documentation as UTF-8 encoded Markdown bytes.

        Args:
            content: Markdown content string.
            filename: Target filename (not used in output, just for reference).

        Returns:
            UTF-8 bytes of the markdown content.
        """
        return content.encode("utf-8")

    def to_html(self, content: str, title: str = "Documentation") -> bytes:
        """
        Convert Markdown content to a styled HTML document.

        Args:
            content: Markdown content string.
            title: Page title for the HTML document.

        Returns:
            UTF-8 bytes of the HTML document.
        """
        try:
            import markdown as md_lib

            extensions = ["tables", "fenced_code", "codehilite", "toc"]
            body = md_lib.markdown(content, extensions=extensions)
        except ImportError:
            # Fallback: wrap in <pre> if markdown lib not available
            body = f"<pre>{content}</pre>"

        html = HTML_TEMPLATE.format(title=title, body=body)
        return html.encode("utf-8")

    def to_zip(self, docs_dict: dict[str, str]) -> bytes:
        """
        Bundle multiple documentation files into a ZIP archive.

        Args:
            docs_dict: Dict mapping filename → content string.

        Returns:
            ZIP archive as bytes.
        """
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for filename, content in docs_dict.items():
                zf.writestr(filename, content.encode("utf-8"))
        buf.seek(0)
        return buf.read()
